# テンプレート形式のバージョン
AWSTemplateFormatVersion: 2010-09-09

Description: VPC For LenSentApp

Resources:
  ECSSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      VpcId: !ImportValue LenSentVPCName
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: ECSSubnet4fromcf
  ECSSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      VpcId: !ImportValue LenSentVPCName
      CidrBlock: 10.0.4.0/24
      Tags:
        - Key: Name
          Value: ECSSubnet4fromcf
  ECSSubnet3RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue LenSentVPCName
      Tags:
        - Key: Name
          Value: ECSSubnet3RTfromcf
  ECSSubnet4RT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue LenSentVPCName
      Tags:
        - Key: Name
          Value: ECSSubnet3RTfromcf
  ECSSubnet3ToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ECSSubnet3RT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !ImportValue IGWName
  AssoECSSubnet3RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ECSSubnet3
      RouteTableId: !Ref ECSSubnet3RT
  ECSSubnet2ToInternet:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref ECSSubnet4RT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !ImportValue IGWName
  AssoECSSubnet2RT:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ECSSubnet4
      RouteTableId: !Ref ECSSubnet4RT

Outputs:
  ECSSubnet3:
    Value: !Ref ECSSubnet3
    Export:
      Name: ECSSubnet3Name
  ECSSubnet4:
    Value: !Ref ECSSubnet4
    Export:
      Name: ECSSubnet4Name
